### ISSUE TITLE
Mapping polymorphic values

### ISSUE THREAD

**Issue by mmottl** [janestreet/ppx_fields_conv#1]
One useful feature that the fields and variants converters are missing is how to perform structure-preserving maps, e.g. (using `fmap` in Haskell-spirit):

``` ocaml
type ('a, 'b) t = { foo : 'a; bar : 'b option } with fields
```

The above would produce a function with the following sigature:

``` ocaml
val fmap : a : ('a1 -> 'a2) -> b : ('b1 -> 'b2) -> ('a1, 'b1) t -> ('a2, 'b2) t
```

Maybe such a feature could also be implemented in a separate preprocessor library.

**Comment by sliquister** [comment]
The `'b option` bit of your example shows that this is something not related to ppx_fields_conv or ppx_variants_conv, as such a preprocessor should work on abstract types (in signatures) and type aliases in signatures and structures, neither of which are supported by ppx_fields_conv and ppx_variants_conv. So as you suggest at the end, a separate preprocessor would be better suited.

I'm going to close this, as we don't plan on writing such a processor. There is a visitors ppx that does a significantly more powerful version of this as I understand, although it's perhaps rather heavy at compile time and runtime for a trivial copy.
