### ISSUE TITLE
Relaxing "at least one record" restriction

### ISSUE THREAD

**Issue by ozanvos** [janestreet/ppx_fields_conv#3]
I'd like to use ppx_fields_conv with [atdgen](https://github.com/mjambon/atd) but `check_at_least_one_record` calls prevent it since `-deriving-conv fields` flag appends `[@@deriving fields]` to each type including variants. 

Removing the check works well, non-applicable types seem to be silently ignored. Is it possible to relax this restriction?

**Comment by diml** [comment]
What is `-deriving-conv`?

**Comment by osener** [comment]
@diml it's an atdgen flag for specifying `ppx_deriving` plugins to use with generated types:

```
  -deriving-conv 
    GEN1,GEN2,...
         Insert 'with GEN1, GEN2, ...' after OCaml type definitions for the
         ppx_deriving preprocessor
 ```
