### ISSUE TITLE
Unused module Direct/Fields error

### ISSUE THREAD

**Issue by copy** [janestreet/ppx_fields_conv#4]
I would like to use deriving fields, but not expose the `Direct` or `Fields` modules. This results in an error like this:

```
File "/tmp/test.ml", line 76, characters 7-8:
Error (warning 60): unused module Direct.
File "/tmp/test.ml", line 76, characters 7-8:
Error (warning 60): unused module Fields.
```

Would it be possible to generate a `[@@@ocaml.warning "-60"]` on these modules or add an option to not generate them in the first place?

**Comment by sliquister** [comment]
Hum, apparently we turn off warning 60, which explains why we don't see this.
Without thinking too long about this, I think both suggestions make sense. We already silence all value level and type level warnings, we might as well silence the module ones too.  For the second suggestion, we want a way to just get a subset of the values to reduce bloat anyway.

**Comment by sliquister** [comment]
(closed because it is fixed at the tip of the repo)
